version: 0.2

env:
  variables:
    FUNCTION_NAME: "lambda-go-hola"
    ALIAS_NAME: "live"

phases:
  install:
    commands:
      - echo "Installing awscli"
      - apt-get update -y
      - apt-get install -y awscli unzip

  build:
    commands:
      - echo "Preparing deploy artifact"
      - echo "Build artifact directory $CODEBUILD_SRC_DIR_Build"
      - cp $CODEBUILD_SRC_DIR_Build/lambda.zip .
      - ls -la
      - echo "Updating function code"
      - aws lambda update-function-code --function-name "$FUNCTION_NAME" --zip-file fileb://lambda.zip

      - echo "Publishing version"
      - VER=$(aws lambda publish-version --function-name "$FUNCTION_NAME" --query Version --output text)
      - echo "Published version $VER"

      - echo "Updating alias $ALIAS_NAME"
      - aws lambda update-alias --function-name "$FUNCTION_NAME" --name "$ALIAS_NAME" --function-version "$VER" \
        || aws lambda create-alias --function-name "$FUNCTION_NAME" --name "$ALIAS_NAME" --function-version "$VER"

artifacts:
  files:
    - '**/*'