version: 0.2

phases:
  install:
    commands:
      - echo "Deploy phase started"
      - ls -R .

  build:
    commands:
      - echo "Buscando lambda.zip en artifact..."
      - ZIP_PATH=$(find . -name "lambda.zip" | head -n 1)
      - echo "ZIP encontrado en $ZIP_PATH"

      - echo "Actualizando Lambda..."
      - aws lambda update-function-code \
          --function-name lambda-go-hola \
          --zip-file fileb://$ZIP_PATH

      - echo "Publicando nueva version..."
      - VERSION=$(aws lambda publish-version --query Version --output text)
      - echo "Version $VERSION"

      - echo "Actualizando alias live..."
      - aws lambda update-alias \
          --function-name lambda-go-hola \
          --name live \
          --function-version $VERSION

artifacts:
  files:
    - "**/*"